"""empty message

Revision ID: 0fc8d3cd85bd
Revises: a17cb76adebf
Create Date: 2026-03-25 21:21:50.463614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc8d3cd85bd'
down_revision = 'a17cb76adebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lan_accommodation_proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_id', sa.BigInteger(), nullable=True))

    with op.batch_alter_table('lan_game_proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_id', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lan_game_proposals', schema=None) as batch_op:
        batch_op.drop_column('message_id')

    with op.batch_alter_table('lan_accommodation_proposals', schema=None) as batch_op:
        batch_op.drop_column('message_id')

    # ### end Alembic commands ###
