"""empty message

Revision ID: 109332581515
Revises: 37bf3313e9d3
Create Date: 2025-07-30 17:03:24.057497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109332581515'
down_revision = '37bf3313e9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_id', sa.String(length=25), nullable=True))
        batch_op.drop_column('custom_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('image_id')
        batch_op.drop_column('url')

    # ### end Alembic commands ###
