"""empty message

Revision ID: 2b81de74ead7
Revises: defbc726e705
Create Date: 2024-04-25 16:59:02.801675

"""
from sqlalchemy_searchable import sync_trigger, drop_trigger
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '2b81de74ead7'
down_revision = 'defbc726e705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
        sa.Column('steam_appid', sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True),
        sa.PrimaryKeyConstraint('steam_appid')
    )

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index('ix_games_search_vector', ['search_vector'], unique=False, postgresql_using='gin')

    sync_trigger(op.get_bind(), 'games', 'search_vector', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    drop_trigger(op.get_bind(), 'games', 'search_vector')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index('ix_games_search_vector', postgresql_using='gin')

    op.drop_table('games')
    # ### end Alembic commands ###
