"""empty message

Revision ID: 37bf3313e9d3
Revises: 3ef8ccb09351
Create Date: 2024-06-11 17:38:24.405970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37bf3313e9d3'
down_revision = '3ef8ccb09351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('custom_url')

    # ### end Alembic commands ###
