"""empty message

Revision ID: b5e95f0b58a3
Revises: f44bc41c09bc
Create Date: 2024-06-04 11:38:44.336033

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b5e95f0b58a3'
down_revision = 'f44bc41c09bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TYPE langameproposalvotetype RENAME TO votetype;')
    op.execute('ALTER TABLE lan_game_proposal_votes ALTER COLUMN type TYPE votetype USING type::votetype;')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TYPE votetype RENAME TO langameproposalvotetype;')
    op.execute('ALTER TABLE lan_game_proposal_votes ALTER COLUMN type TYPE langameproposalvotetype USING type::langameproposalvotetype;')

    # ### end Alembic commands ###
