"""empty message

Revision ID: c1113ed21353
Revises: c48ac1d577b8
Create Date: 2026-03-19 13:04:36.403076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1113ed21353'
down_revision = 'c48ac1d577b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lan_accommodation_proposals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('listing_url', sa.String(length=500), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('location_url', sa.String(length=500), nullable=False),
    sa.Column('bedrooms', sa.SmallInteger(), nullable=False),
    sa.Column('single_beds', sa.SmallInteger(), nullable=False),
    sa.Column('twin_beds', sa.SmallInteger(), nullable=False),
    sa.Column('large_tables', sa.SmallInteger(), nullable=True),
    sa.Column('has_fiber', sa.Boolean(), nullable=True),
    sa.Column('has_private_parking', sa.Boolean(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lan_accommodation_proposal_votes',
    sa.Column('accommodation_proposal_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('type', sa.Enum('YES', 'NEUTRAL', 'NO', name='accommodationvotetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_proposal_id'], ['lan_accommodation_proposals.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('accommodation_proposal_id', 'user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    op.drop_table('lan_accommodation_proposal_votes')
    op.drop_table('lan_accommodation_proposals')

    op.execute('DROP TYPE accommodationvotetype;')
    # ### end Alembic commands ###
