"""empty message

Revision ID: c547abec2d5f
Revises: 0fc8d3cd85bd
Create Date: 2026-03-28 22:03:02.688564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c547abec2d5f'
down_revision = '0fc8d3cd85bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        kitchen_enum = sa.Enum('COOK', 'ASSISTANT', 'ANY', name='userkitchenpreference')
        kitchen_enum.create(batch_op.get_bind(), checkfirst=True)

        water_enum = sa.Enum('STILL', 'SPARKLING', 'ANY', name='userwaterpreference')
        water_enum.create(batch_op.get_bind(), checkfirst=True)

        hot_drinks_enum = sa.Enum('COFFEE', 'TEA', 'HOT_CHOCOLATE', 'ANY', 'NONE', name='userhotdrinkspreference')
        hot_drinks_enum.create(batch_op.get_bind(), checkfirst=True)

        breakfast_enum = sa.Enum('SWEET', 'SALTY', 'ANY', name='userbreakfastpreference')
        breakfast_enum.create(batch_op.get_bind(), checkfirst=True)

        breads_enum = sa.Enum('WHITE', 'WHOLE_GRAIN', 'ANY', name='userbreadspreference')
        breads_enum.create(batch_op.get_bind(), checkfirst=True)

        alcohol_enum = sa.Enum('WINE', 'BEER', 'ANY', 'NONE', name='useralcoholpreference')
        alcohol_enum.create(batch_op.get_bind(), checkfirst=True)

        chicken_enum = sa.Enum('THIGHS', 'BREAST', 'ANY', 'NONE', name='userchickenpreference')
        chicken_enum.create(batch_op.get_bind(), checkfirst=True)

        dry_sausage_enum = sa.Enum('REGULAR', 'CHORIZO', 'ANY', 'NONE', name='userdrysausagepreference')
        dry_sausage_enum.create(batch_op.get_bind(), checkfirst=True)

        pate_enum = sa.Enum('REGULAR', 'RILLETTES', 'ANY', 'NONE', name='userpatepreference')
        pate_enum.create(batch_op.get_bind(), checkfirst=True)

        batch_op.add_column(sa.Column('allergies', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('special_diet', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_vegetarian', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('kitchen', kitchen_enum, nullable=True))
        batch_op.add_column(sa.Column('water', water_enum, nullable=True))
        batch_op.add_column(sa.Column('hot_drinks', hot_drinks_enum, nullable=True))
        batch_op.add_column(sa.Column('breakfast', breakfast_enum, nullable=True))
        batch_op.add_column(sa.Column('breads', breads_enum, nullable=True))
        batch_op.add_column(sa.Column('cheeses', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('spicy_dishes', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('alcohol', alcohol_enum, nullable=True))
        batch_op.add_column(sa.Column('meat', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('chicken', chicken_enum, nullable=True))
        batch_op.add_column(sa.Column('dry_sausage', dry_sausage_enum, nullable=True))
        batch_op.add_column(sa.Column('thai_cuisine', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pate', pate_enum, nullable=True))
        batch_op.add_column(sa.Column('other_preferences', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('other_preferences')
        batch_op.drop_column('pate')
        batch_op.drop_column('thai_cuisine')
        batch_op.drop_column('dry_sausage')
        batch_op.drop_column('chicken')
        batch_op.drop_column('meat')
        batch_op.drop_column('alcohol')
        batch_op.drop_column('spicy_dishes')
        batch_op.drop_column('cheeses')
        batch_op.drop_column('breads')
        batch_op.drop_column('breakfast')
        batch_op.drop_column('hot_drinks')
        batch_op.drop_column('water')
        batch_op.drop_column('kitchen')
        batch_op.drop_column('is_vegetarian')
        batch_op.drop_column('special_diet')
        batch_op.drop_column('allergies')

    op.execute('DROP TYPE userkitchenpreference;')
    op.execute('DROP TYPE userwaterpreference;')
    op.execute('DROP TYPE userhotdrinkspreference;')
    op.execute('DROP TYPE userbreakfastpreference;')
    op.execute('DROP TYPE userbreadspreference;')
    op.execute('DROP TYPE useralcoholpreference;')
    op.execute('DROP TYPE userchickenpreference;')
    op.execute('DROP TYPE userdrysausagepreference;')
    op.execute('DROP TYPE userpatepreference;')

    # ### end Alembic commands ###
