"""empty message

Revision ID: f44bc41c09bc
Revises: db42bea03631
Create Date: 2024-05-21 11:06:20.073954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44bc41c09bc'
down_revision = 'db42bea03631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('name', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.PickleType(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
